<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Message Model
 *
 * Represents a single message in a chat thread.
 * Messages can be sent by guests, agents, or auto-generated (bot).
 * Each message is linked to a chat and optionally to a user (agent/admin).
 *
 * @author Development Team
 *
 * @version 1.0
 *
 * @property int $id
 * @property int $chat_id FK to chat thread
 * @property int|null $user_id FK to user (null for guest messages)
 * @property string $content Message text content
 * @property string $sender Sender type: 'guest', 'agent', 'bot'
 * @property bool $is_auto_reply Whether message was generated by auto-reply rule
 * @property int|null $created_by User who created this record (admin/system)
 * @property int|null $updated_by User who updated this record
 * @property string|null $created_ip IP address of creator
 * @property string|null $updated_ip IP address of updater
 * @property \Illuminate\Support\Carbon $created_at
 * @property \Illuminate\Support\Carbon $updated_at
 */
class Message extends Model
{
    use HasFactory;

    /**
     * Sender types
     */
    public const SENDER_GUEST = 'guest';

    public const SENDER_AGENT = 'agent';

    public const SENDER_BOT = 'bot';

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'chat_id',
        'user_id',
        'content',
        'sender',
        'is_auto_reply',
        'created_by',
        'updated_by',
        'created_ip',
        'updated_ip',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'is_auto_reply' => 'boolean',
            'created_at' => 'datetime',
            'updated_at' => 'datetime',
        ];
    }

    /**
     * Get the chat this message belongs to.
     *
     * @return BelongsTo The parent chat thread
     */
    public function chat(): BelongsTo
    {
        return $this->belongsTo(Chat::class);
    }

    /**
     * Get the user who sent this message (if applicable).
     *
     * Returns null for guest messages or bot-generated messages.
     *
     * @return BelongsTo|null The user (agent/admin) who sent this message
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}
